[build]
  command = """
    python -m pip install --upgrade pip
    pip install -r requirements.txt
    npm install python-shell
  """
  functions = "netlify/functions"
  publish = "."

[[redirects]]
  from = "/*"
  to = "/.netlify/functions/app"
  status = 200
  force = true

[functions]
  directory = "netlify/functions"
  node_bundler = "esbuild"
  external_node_modules = ["python-shell"]

[build.environment]
  PYTHON_VERSION = "3.9"
  PYTHON_PATH = "python3.9"
